spring.application.name=citasBackend
spring.datasource.url=jdbc:mysql://localhost:3307/citas?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=isrra123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

