spring.application.name=citasBackend
spring.datasource.url=jdbc:mysql://localhost:3307/citas?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=isrra123
server.port=8010
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Se cambiara esta clave mas tarde
app.jwt.secret=miClaveSecretaSuper123456789SecretaParaFirmarTokens  
app.jwt.expiration=86400000

#Configuracion para envio de mensajes por WhatsApp
whatsapp.api.url=https://graph.facebook.com/v18.0
whatsapp.api.phone-number-id=884707731390130
#Este token tienen una duracion de 24 hrs
whatsapp.api.access-token=EAAMSTOrH5ZCQBPw8G7jrtu3OFW5XKE34mqwZBkTmhFFkVo5rjhCnxNr7VUJfuWMC4QlTrsZB1tvpZA6bBEvOpOqYd6477CiNHp1pMOVbaqZA6ZAhifZCDzoNKQCCuWsuTIZBtPx3LBmmaBfMacS0kzifk8Pp90IL9nb6HzurTi96y5csybPGjB7V5K6fxPYTKY4QY0l52ZAp9r3JFpedrUS7yWpNrsHEpd6t78wwA9aRZBry1TC6PhcfJgbBviZBz4CW6MhGfwBg1pEZBQ0eRyAFZAdB8mgLj
whatsapp.api.template-name=confirmacion_cita
whatsapp.api.template-language=es_MX
whatsapp.api.use-template-params=false


